# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
name: Project / Size PR

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]

jobs:
  update_labels:
    runs-on: ubuntu-latest
    steps:
    - name: Monitor Actions
      uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ vars.PERMISSIONS_CONFIG }}

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - uses: codelytv/pr-size-labeler@4ec67706cd878fbc1c8db0a5dcd28b6bb412e85a # v1.10.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_max_size: '10'
        s_max_size: '100'
        m_max_size: '500'
        l_max_size: '1000'
        fail_if_xl: 'false'
        # message_if_xl: 'This looks like a MAJOR change 😊'

    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        github_token: ${{ secrets.github_token }}
        labels: ${{ steps.size.outputs.stale_labels }}

    - uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.github_token }}
        labels: ${{ steps.size.outputs.new_label }}
